import numpy as n
a=n.array([54,78,32,46,89,76])
print("\nAn Array:",a)
print("\nsum:",n.sum(a))
print("product",n.prod(a))
print("mean:",n.mean(a))
print("Standard Deviation:",n.std(a))
print("variance",n.var(a))
print("minimum value:",n.min(a))
print("max:",n.max(a))
print("min Index:",n.argmin(a))
print("max Index:",n.argmax(a))
print("median:",n.median(a))
print("product:",n.prod(a))
